baseURL = ""
languageCode = "en-us"
title = "Amoro"
theme = "amoro-theme"
sectionPagesMenu = "main"

[params]
  siteType = "landing-page"
  search = true
  description = "Amoro is a Lakehouse management system built on open data lake formats."
  docsBaseURL = ""
  githuburl = "https://github.com/Netease/arctic"

[[params.social]]
  title = "Github"
  icon = "github-fill"
  url = "https://github.com/NetEase/arctic"
[[params.social]]
  title = "Issue Tracking"
  icon = "slack-square-fill"
  url = "https://github.com/NetEase/arctic/issues"
[[params.social]]
  title = "Wechat"
  icon = "wechat-fill"
  url = "javascript:void();"

[[params.features]]
  title = "Self-managed"
  desc = "Automatically compact small files and change files, regularly delete expired data to ensure the quality of table queries, and reduce system costs."
  icon = "Self-managed"
[[params.features]]
  title = "Multiple Formats"
  desc = "Support different table formats to meet different scenario requirements and provide them with unified management capabilities."
  icon = "Multiple-Formats"
[[params.features]]
  title = "Catalog Service"
  desc = "Provide a unified metadata management service for all computing engines, which can also be combined with existing metadata services."
  icon = "Catalog-Service"
[[params.features]]
  title = "Rich Plugins"
  desc = "Support different table formats to meet different scenario requirements and provide them with unified management capabilities."
  icon = "Rich-Plugins"
[[params.features]]
  title = "Management tools"
  desc = "Visual management tools provide rich monitoring and management capabilities to help users get started easily."
  icon = "Management-tools"
[[params.features]]
  title = "Infrastructure Idependent"
  desc = "Can be easily deployed and used in private environments, cloud environments, hybrid cloud environments, and multi-cloud environments."
  icon = "Infrastructure-Idependent"

[outputFormats.SearchIndex]
baseName = "landingpagesearch"
mediaType = "application/json"

[outputs]
home = [ "HTML", "RSS", "SearchIndex" ]

[menu]

  topnav = [
    { name = "Quickstart", weight = 100 },
    { name = "Setup", parent = "Quickstart", url = "/quickstart-setup/", weight = 101 },
    { name = "Quick Demo", parent = "Quickstart", url = "/quick-demo/", weight = 102 },
    { name = "Docs", weight = 200 },
    { name = "0.5.0", parent = "Docs", url = "/docs/latest/", weight = 201 },
    { name = "Benchmark", weight = 300 },
    { name = "Benchmark Report", parent = "Benchmark", url = "/benchmark-report/", weight = 301 },
    { name = "Benchmark Guide", parent = "Benchmark", url = "/benchmark-guide/", weight = 302 },
    { name = "Download", url = "/download/", weight = 400 },
    { name = "Roadmap", url = "/roadmap/", weight = 500 },
    { name = "Community", weight = 600 },
    { name = "Join Community", parent = "Community", url = "/join-community/", weight = 601 },
    { name = "How to contribute", parent = "Community", url = "/how-to-contribute/", weight = 602 },
  ]

[markup.goldmark.renderer]
unsafe= true
