baseURL = ""
canonifyURLs = "true"
relativeURLs = "true"
languageCode = "en-us"
title = "Amoro"
theme= "amoro-theme"

[params]
  siteType = "docs"
  search = true
  versions.iceberg = "" # This is populated by the github deploy workflow and is equal to the branch name
  versions.nessie = "0.59.0"
  latestVersions.iceberg = "0.5.0"  # This is used for the version badge on the "latest" site version
  BookSection='docs' # This determines which directory will inform the left navigation menu
  disableHome=true

[outputFormats.SearchIndex]
baseName = "search"
mediaType = "application/json"

[outputs]
home = [ "HTML", "RSS", "SearchIndex" ]

[menu]

  topnav = [
    { name = "Quickstart", weight = 100 },
    { name = "Setup", parent = "Quickstart", pre = "relative", url = "../../quickstart-setup/", weight = 101 },
    { name = "Quick Demo", parent = "Quickstart", pre = "relative", url = "../../quick-demo/", weight = 102 },
    { name = "Docs", weight = 200 },
    { name = "0.5.0", parent = "Docs", pre = "relative", url = "../../docs/latest/", weight = 201 },
    { name = "Benchmark", weight = 300 },
    { name = "Benchmark Report", parent = "Benchmark", pre = "relative", url = "../../benchmark-report/", weight = 301 },
    { name = "Benchmark Guide", parent = "Benchmark", pre = "relative", url = "../../benchmark-guide/", weight = 302 },
    { name = "Download", pre = "relative", url = "../../download/", weight = 400 },
    { name = "Roadmap", pre = "relative", url = "../../roadmap/", weight = 500 },
    { name = "Community", weight = 600 },
    { name = "Join Community", parent = "Community", pre = "relative", url = "../../join-community/", weight = 601 },
    { name = "How to contribute", parent = "Community", pre = "relative", url = "../../how-to-contribute/", weight = 602 },
  ]

  main = [ # Main menu, docs site left nav
    { name = "Introduction", url = "/", weight = 1},
    { name = "Concepts", weight = 100 },
    { name = "Admin Guides", weight = 200},
    { name = "User Guides", weight = 300},
    { name = "Formats", weight = 400 },
    { name = "Flink", weight = 500},
    { name = "Spark", weight = 600},
  ]

[markup.goldmark.renderer]
unsafe= true